# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true


[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/pangfq"


[social.params]
icon = "brand-github"

[params.social]
   a-email = "mailto:a9qr21@gmail.com"
